service: analyze-image

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  timeout: 30
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - '*'
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'

functions:
  analyze-image:
    handler: index.handler
    events:
      - http:
          path: /analyze-image
          method: post
          cors: true
