service: analyze-image

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  timeout: 30
  role: arn:aws:iam::988615802188:role/lambda-vpc-role
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - '*'
    - Effect: 'Allow'
      Action:
        - 'ses:SendEmail'
      Resource:
        - 'arn:aws:ses:us-east-1:988615802188:identity/info@lagrangetechologies.com'
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'

functions:
  analyze-image:
    handler: index.handler
    events:
      - http:
          path: /analyze-image
          method: post
          cors: true
