service: analyze-image

plugins:
  - serverless-offline
  - serverless-plugin-typescript

package:
  exclude:
    - node_modules/**
    - '!node_modules/node-fetch/**'
    - '!node_modules/serverless-http/**'
    - '!node_modules/@tensorflow/tfjs/**'
    - '!node_modules/ramda/**'
    - '!node_modules/express/**'
    - '!node_modules/body-parser/**'
    - '!node_modules/cors/**'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  timeout: 30
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - '*'
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'

functions:
  analyze-image:
    handler: index.handler
    events:
      - http:
          path: /analyze-image
          method: post
          cors: true
